kind: Service
apiVersion: v1
metadata:
  name: noteapp-service
  namespace: noteapp-namespace
spec:
  selector:
    app: noteapp
  ports:
   - protocol: TCP
     port: 8000
     targetPort: 8000
  type:  ClusterIP
